// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSB0Up7ktbVQmcnb9Weujj2XcFd4lfn1c',
    appId: '1:723344906216:web:9f7f81bca79a952831f65d',
    messagingSenderId: '723344906216',
    projectId: 'sanku-pro',
    authDomain: 'sanku-pro.firebaseapp.com',
    storageBucket: 'sanku-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkxbNT7c_6y0d-DfYiduzMDf9RzI119-Q',
    appId: '1:723344906216:android:1a515415d953759c31f65d',
    messagingSenderId: '723344906216',
    projectId: 'sanku-pro',
    storageBucket: 'sanku-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGIVvNeX7kLEechme2G8xIxT_EHdEXIAw',
    appId: '1:723344906216:ios:89d394b09a02494831f65d',
    messagingSenderId: '723344906216',
    projectId: 'sanku-pro',
    storageBucket: 'sanku-pro.firebasestorage.app',
    iosBundleId: 'com.example.sankuPro',
  );
}
